### ISSUE TITLE
Launcher icon disappears when changing app icon

### ISSUE THREAD

**Issue by stefankp** [skb1129/react-native-change-icon#13]
@skb1129 this works great, thank you. 

Android uses the `name` of the `activity` (or `activity-alias`) when you add a shortcut for the app to the home screen. Since we need unique names for each `activity-alias`, the previously added shortcut disappears every time the icon is changed. 

Have you found a workaround for that issue?

**Comment by skb1129** [comment]
Yeah, this is how we use it in our application:
```
        <activity
            android:name=".MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:exported="true"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustPan">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
           </intent-filter>
        </activity>

        <activity-alias
            android:name="com.evivernappv0.MainActivityicon"
            android:enabled="true"
            android:icon="@mipmap/icon"
            android:roundIcon="@mipmap/icon_round"
            android:targetActivity=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity-alias>
        <activity-alias
            android:name="com.evivernappv0.MainActivityalternate"
            android:enabled="false"
            android:icon="@mipmap/alternate"
            android:roundIcon="@mipmap/alternate_round"
            android:targetActivity=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity-alias>
```
Note that I changed action MAIN to VIEW in for the MainActivity and set `android:enable="true"` only for the first `activity-alias`. This way the first `activity-alias` is displayed on the home screen and the main `activity` is never displayed.

**Comment by stefankp** [comment]
@skb1129 I still have the issue, that the app shortcut is removed from the home screen when I change the icon. The shortcut is tied to the `android:name` which is different for each activity and activity-alias 🤔 

This doesn't happen with your app?

**Comment by kamwoz** [comment]
I have the same problem. For user its showing like new app, but with different icon

**Comment by skb1129** [comment]
@stefankp Yeah, the shortcut icon on the Home screen however will always be removed whenever the icon is switched. This is one of the drawback and I haven’t found any workaround for this as the alternate icon feature is not actually supported by Android.

**Comment by stefankp** [comment]
@skb1129 Ok. I am fine with that drawback, was just wondering if you have a solution. 

Thank you.
