### ISSUE TITLE
null is not an object (evaluating..)

### ISSUE THREAD

**Issue by Relax594** [skb1129/react-native-change-icon#20]
**Platform**
 - [ X ] iOS
 - [ not tested ] Android

**Description**
App is crashing when trying to change the icon.

`error calling specific saga generator function [TypeError: null is not an object (evaluating '_reactNative.NativeModules.ChangeIcon.changeIcon')]`

**To Reproduce**
1.
2.

**Expected behavior**
App Icon's changing

**Screenshots**

Structure is like this:
![image](https://user-images.githubusercontent.com/22765758/93746865-1ae58f00-fbf6-11ea-9945-9688f83f5861.png)

Info.plist:
![image](https://user-images.githubusercontent.com/22765758/93747022-5d0ed080-fbf6-11ea-97a2-256ba976250f.png)

**Device (please complete the following information):**
 - Device: [iPad mini]
 - OS: [iOS 14.0]

**Versions**
 - react-native: [0.63.2]
 - react-native-change-icon: [3.0.0]

**Code Snippet**
```
useEffect(() => {
        if (institut === persistedInstitut) return;
        if (institut !== 'MNSOSA') changeIcon('bav');
        else changeIcon('oesa');
    }, [institut]);
```

**Comment by skb1129** [comment]
@Relax594, the key in `Info.plist` should be `CFBundleAlternateIcons`, you misspelt it.

**Comment by Relax594** [comment]
Fixed, same issue.

**Comment by Relax594** [comment]
I also get this warning now: 

`Module ChangeIcon requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.`

**Comment by Relax594** [comment]
Okay, i managed to do it on the iPhone now. How can we support multiple devices (e.g. iPhone and iPad)?
