### ISSUE TITLE
changeIcon(null) does not reset to default

### ISSUE THREAD

**Issue by Relax594** [skb1129/react-native-change-icon#21]
**Platform**
 - [ X ] iOS
 - [ not tested ] Android

**Description**
calling `changeIcon(null)` does not reset the app icon to default

**To Reproduce**
1. change app icon to some alternate
2. try to set it to default with `changeIcon(null)`

**Expected behavior**
App Icon back to default

**Screenshots**

**Device (please complete the following information):**
 - Device: [iPhone 11 Pro Max Simulator, iPad mini Device]
 - OS: [iOS 14.0]

**Versions**
 - react-native: [0.63.2]
 - react-native-change-icon: [3.0.0]

**Code Snippet**
Please provide a minimal code snippet of the setup that you did to use this package. [e.g. AndroidManifest.xml]

**Comment by skb1129** [comment]
@Relax594 In Android there is no functionality to reset the icon to default, you always need to pass an activity-alias icon to display. Which is why passing `null` to `changeIcon` will not work on iOS too, just because we need to maintain the cross platform functionality.

**Comment by Relax594** [comment]
So i always have to add the default icons into the AppIcons folder aswell?

**Comment by skb1129** [comment]
Yes, that is correct @Relax594

**Comment by Relax594** [comment]
Thanks.
