### ISSUE TITLE
Not working on IOS

### ISSUE THREAD

**Issue by MuhammetAdamoglu** [skb1129/react-native-change-icon#23]
**Platform**
 - [x] iOS
 - [ ] Android

When I change the icon, I get an alert like "icon has been changed" but there is no change in the icon. Can you review the screenshot I shared below and help me find out where I went wrong?

<img width="399" alt="Ekran Resmi 2020-10-26 15 37 41" src="https://user-images.githubusercontent.com/35458717/97173188-d28f3300-1798-11eb-9f12-eb6d09e541cf.png">

<img width="492" alt="Ekran Resmi 2020-10-26 15 37 21" src="https://user-images.githubusercontent.com/35458717/97173222-e0dd4f00-1798-11eb-99a5-cad7a4bf5159.png">

**Comment by MuhammetAdamoglu** [comment]
ok, I understood my problem

**Comment by afgarcia86** [comment]
@MuhammetAdamoglu I am having the same problem can you explain what you did to fix it?

**Comment by MuhammetAdamoglu** [comment]
@afgarcia86 
<img width="207" alt="Ekran Resmi 2021-01-18 21 31 09" src="https://user-images.githubusercontent.com/35458717/104951902-825cf100-59d4-11eb-9293-5c735f3d5fe1.png">
Hi, 
I changed the icon name to icon_name@2x.png and icon_name@3x.png. I'm not sure that this is the solution to the error. If it doesn't work, tell me tomorrow I will examine it in detail.

**Comment by afgarcia86** [comment]
That was it thanks!

**Comment by cutenesss** [comment]
hi. even with the correct icon name, my app icon shows no change. is there any other things i should considers?

**Comment by sohail-dragon** [comment]
> hi. even with the correct icon name, my app icon shows no change. is there any other things i should considers?

Might be a little late, but I had a debug.plist which needed to be updated as well. Maybe it helps you. If you haven't already found a solution that is 😛
