### ISSUE TITLE
Warning about missing implementation of requiresMainQueueSetup

### ISSUE THREAD

**Issue by mitjaz** [skb1129/react-native-change-icon#24]
**Platform**
 - [X] iOS
 - [ ] Android

**Description**
A warning is shown that the module does not implement requiresMainQueueSetup. 
`Module ChangeIcon requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.`

**To Reproduce**
1. Install a react-native-change-icon on a fresh initialized project

**Expected behavior**
Not to display the warning

**Screenshots**
<img width="424" alt="Screenshot 2020-11-09 at 17 00 42" src="https://user-images.githubusercontent.com/5383924/98564929-43f8d680-22ad-11eb-8ba6-9db2154038a2.png">

**Device (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.3

**Versions**
 - react-native: 0.63.3
 - react-native-change-icon: 3.0.0

**Comment by skb1129** [comment]
@mitjaz guys I have just released a beta version fixing this issue, please try it once, if this works then I'll create a major release on NPM.

**Comment by sjusaitis** [comment]
Worked for me! thanks

**Comment by skb1129** [comment]
Closing this issue, it has been fixed.
