### ISSUE TITLE
Can I select the app icon from the Network/URL

### ISSUE THREAD

**Issue by phithu** [skb1129/react-native-change-icon#33]
Hi @skb1129, thank for creating great lib. I want to select the app icon from the network or URL. Do you have idea to implement this feature? Thanks

**Comment by skb1129** [comment]
Hey @phithu, I did try to find a way to do this when I was initially creating this package but I could not find a way to do this. Every documentation seems to point that the icons should be inside the application bundle itself, it cannot be fetched from a remote server. This goes for both Android and iOS applications.
If you do find some resources that show how to get the app icons from a network, please do let me know, I would surely follow up on that.
