### ISSUE TITLE
Alternate icon not supported

### ISSUE THREAD

**Issue by MarvinVk** [skb1129/react-native-change-icon#36]
**Platform**
 - [X] iOS
 - [ ] Android

**Description**
It does not work anymore to change the icons on iOS. It displays the error `Alternate icon not supported`. 
It always worked fine until recently. I did not change anything in the code so I was wondering if someone knows anything about a recent update from iOS? Is there anyone that faces the same issue?

**To Reproduce**
1. macOS Big Sur Version 11.4
2. Xcode Version 12.5

**Expected behavior**
To be still be able to change icons on iOS

**Screenshots**
![Simulator Screen Shot - iPhone 12 - 2021-06-11 at 14 45 07](https://user-images.githubusercontent.com/2162972/121688457-c5267f00-cac3-11eb-8bfe-7a8b446fc147.png)

**Device (please complete the following information):**
 - Device: All iPhones and iOS emulators
 - OS: iOS 14.5

**Versions**
 - react-native: 0.64.0
 - react-native-change-icon: 3.0.0

**Code Snippet**
Please provide a minimal code snippet of the setup that you did to use this package. [e.g. AndroidManifest.xml]

**Comment by joseAMesaS** [comment]
Having the same issue! same versions.

**Comment by zachgibson** [comment]
Seems like your system doesn't support changing app icons. [Here's](https://github.com/skb1129/react-native-change-icon/blob/master/ios/ChangeIcon.swift#L13) where the error gets thrown and [here](https://developer.apple.com/documentation/uikit/uiapplication/2806815-supportsalternateicons) is the UIKit instance property documentation.

**Comment by zachgibson** [comment]
@MarvinVk one thing I'm wondering is maybe your `info.plist` needs to be changed/fixed? iOS 14.5 supports this feature.

**Comment by zachgibson** [comment]
Actually no, that doesn't make sense because the property is just a boolean and this error gets thrown if it is false. Let me install this module and see if it works for me.

**Comment by zachgibson** [comment]
So I just installed `"react-native-change-icon": "^3.0.0"` and ran on iPhone 12 mini simulator running iOS 14.5 and it works. Not sure why you env is saying alternate icons are not supported.

**Comment by skb1129** [comment]
@MarvinVk can you please share your `info.plist` file?
Please refer to the Example application in the repository, it is tried and tested and it seems to be working just fine.

**Comment by MarvinVk** [comment]
This is my `info.plist`:
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleGetInfoString</key>
	<string>0.3.0</string>
	<key>CFBundleIcons</key>
	<dict>
		<key>CFBundleAlternateIcons</key>
		<dict>
			<key>CFBundlePrimaryIcon</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>default</string>
				</array>
			</dict>
			<key>aberkyn</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>aberkyn</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
			<key>almere</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>almere</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
			<key>bam</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>bam</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
			<key>ggzdrenthe-inbalans</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>ggzdrenthe-inbalans</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
			<key>inbalans</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>inbalans</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
			<key>inhealth</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>inhealth</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
			<key>jijbijdeltion</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>jijbijdeltion</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
			<key>jouwmoment</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>jouwmoment</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
			<key>mondriaan</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>mondriaan</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
			<key>myjourney</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>myjourney</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
			<key>nijmegen</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>nijmegen</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
			<key>nvd</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>nvd</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
			<key>odbn</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>odbn</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
			<key>schiedam</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>schiedam</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
			<key>wmr</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>wmr</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<false/>
			</dict>
		</dict>
	</dict>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>Bundle Id</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>myjourney</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>We use your camera so you can take of photo of what you would like to post.</string>
	<key>NSFaceIDUsageDescription</key>
	<string>Enabling Face ID allows you quick and secure access to your account.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string></string>
	<key>NSMicrophoneUsageDescription</key>
	<string>We use your microphone to give you the ability to add audio to your posts.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>We use your photos to show your profile picture and to share photos with other users. Only you decide when and where to share photos in the app.</string>
	<key>UIAppFonts</key>
	<array>
		<string>Inter-Bold.ttf</string>
		<string>Inter-SemiBold.ttf</string>
		<string>Inter-Medium.ttf</string>
		<string>Inter-Regular.ttf</string>
		<string>FontAwesome5_Pro_Brands.ttf</string>
		<string>FontAwesome5_Pro_Light.ttf</string>
		<string>FontAwesome5_Pro_Regular.ttf</string>
		<string>FontAwesome5_Pro_Solid.ttf</string>
		<string>Inter-Black.ttf</string>
		<string>Inter-BlackItalic.ttf</string>
		<string>Inter-BoldItalic.ttf</string>
		<string>Inter-ExtraBold.ttf</string>
		<string>Inter-ExtraBoldItalic.ttf</string>
		<string>Inter-Italic.ttf</string>
		<string>Inter-MediumItalic.ttf</string>
		<string>Inter-SemiBoldItalic.ttf</string>
	</array>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>LaunchScreen</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UIRequiresFullScreen</key>
	<true/>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>
`

**Comment by skb1129** [comment]
@MarvinVk the `CFBundlePrimaryIcon` key should be on the same level as `CFBundleAlternateIcons` key. Currently, it is inside the `CFBundleAlternateIcons` dict.

**Comment by skb1129** [comment]
Closing as inactive
