### ISSUE TITLE
Empty Icon after setting the default

### ISSUE THREAD

**Issue by dancixx** [skb1129/react-native-change-icon#40]
**Platform**
 - [x] iOS
 - [x] Android

**Description**
I try to set the default app icon, but after the `changeIcon` method I get an empty icon.

```
<key>CFBundleIcons</key>
	<dict>
		<key>CFBundleAlternateIcons</key>
		<dict>
			<key>default</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>default</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<string>NO</string>
			</dict>
			<key>sandrahorvath</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>sandrahorvath</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<string>NO</string>
			</dict>
		</dict>
		<key>CFBundlePrimaryIcon</key>
		<dict>
			<key>CFBundleIconFiles</key>
			<array>
				<string>default</string>
			</array>
			<key>CFBundleIconName</key>
			<string></string>
			<key>UIPrerenderedIcon</key>
			<false/>
		</dict>
		<key>UINewsstandIcon</key>
		<dict>
			<key>CFBundleIconFiles</key>
			<array>
				<string>default</string>
			</array>
			<key>UINewsstandBindingEdge</key>
			<string>UINewsstandBindingEdgeLeft</string>
			<key>UINewsstandBindingType</key>
			<string>UINewsstandBindingTypeMagazine</string>
		</dict>
	</dict>
```

**Comment by rohan-kadkol** [comment]
@dancixx I am facing the same issue of the empty app icon even after making my icon images to be `.png` format and not `.jpg` format as you mentioned in https://github.com/skb1129/react-native-change-icon/issues/23#issuecomment-906511228. I also tried other approaches mentioned in https://github.com/skb1129/react-native-change-icon/issues/59#issuecomment-1357672128. That didn't work too.

Can you please help? This is very urgent. Thanks

**Comment by rohan-kadkol** [comment]
> @dancixx I am facing the same issue of the empty app icon even after making my icon images to be `.png` format and not `.jpg` format as you mentioned in [#23 (comment)](https://github.com/skb1129/react-native-change-icon/issues/23#issuecomment-906511228). I also tried other approaches mentioned in [#59 (comment)](https://github.com/skb1129/react-native-change-icon/issues/59#issuecomment-1357672128). That didn't work too.
> 
> Can you please help? This is very urgent. Thanks

I realized the issue. I was new to iOS so I thought that a folder and a group are the same thing. So I pasted the icons in `ios/<Project>/AppIcons` "folder".

What I was missing to do was opening the `ios` folder in XCode and adding the icons from the `ios/Project/AppIcons` folder in the `<Project>/AppIcons` group. This was also mentioned in the [README](https://github.com/skb1129/react-native-change-icon#ios) but I, unfortunately, got confused.

I realized this after cloning and observing the [examples](https://github.com/skb1129/react-native-change-icon/tree/master/example) folder in the repo.

After adding the images to the `<Project>/AppIcons` "group" and not just the `ios/<Project>/AppIcons` folder, it worked! 🎉
