### ISSUE TITLE
Duplicate app in first change icon app

### ISSUE THREAD

**Issue by caolong0204** [skb1129/react-native-change-icon#44]
**Platform**

 -  Android

**Description**
In android, i used code like code in project example
Firstly i change icon app, i see my app is duplicated ,one with old icon and one with new icon
When update icon one more, there will be only an app.

**To Reproduce**
1.Build app and change icon app first
2.back to main screen. and there will be 2 app appear.

**Expected behavior**
there will be always only an app in my devices.

**Screenshots**

<img src="https://user-images.githubusercontent.com/66582805/135645615-51497f27-16ec-40f5-b7ba-4119eeca628e.png" width="400" height="790">

**Versions**
 - react-native: [0.64.0]
 - react-native-change-icon: [3.1.1]

**Code Snippet**
`<activity android:name=".MainActivity" `
            `  android:label="@string/app_name" `
           `   android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" `
         `     android:launchMode="singleTask" `
           `   android:windowSoftInputMode="adjustResize">`
`  <intent-filter>`
  `       <action android:name="android.intent.action.VIEW" />`
 `           <category android:name="android.intent.category.DEFAULT" />`
 `     </intent-filter>`
`</activity>`

**Comment by junioroga** [comment]
I solved this by setting enabled=false for all activity-alias.

**Comment by 0xc14m1z** [comment]
Thanks for the tip @junioroga , but I have the same behavior... double icon.

This is my `AndroidManifest.xml` file, with some omission for confidential reasons:

```xml
<manifest
  xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
  package="com.-omitted-">

  <uses-permission android:name="android.permission.INTERNET" />

  <application
    android:name=".MainApplication"
    android:label="@string/app_name"
    android:icon="@mipmap/standard"
    android:roundIcon="@mipmap/standard_round"
    android:allowBackup="false"
    android:theme="@style/AppTheme"
    android:fullBackupContent="@xml/appcenter_backup_rule">

    <activity
      android:name=".MainActivity"
      android:label="@string/app_name"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
      android:launchMode="singleTask"
      android:screenOrientation="portrait"
      android:windowSoftInputMode="adjustResize"
      android:exported="true">

      <intent-filter>
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
          android:scheme="${applicationId}"
          android:host="${applicationId}"
          android:pathPrefix="/android/callback"
        />
      </intent-filter>

      <intent-filter>
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
          android:scheme="https"
          android:host="-omitted-"
        />
      </intent-filter>

      <intent-filter>
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
          android:scheme="https"
          android:host="-omitted-"
        />
      </intent-filter>

      <intent-filter>
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
          android:scheme="https"
          android:host="-omitted-"
        />
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
          android:scheme="https"
          android:host="-omitted-"
        />
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
          android:scheme="https"
          android:host="-omitted-"
        />
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
          android:scheme="https"
          android:host="-omitted-"
        />
      </intent-filter>
    </activity>

    <activity-alias
      android:name=".MainActivitystandard"
      android:enabled="true"
      android:icon="@mipmap/standard"
      android:roundIcon="@mipmap/standard_round"
      android:targetActivity=".MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity-alias>

    <activity-alias
      android:name=".MainActivitycolorful"
      android:enabled="false"
      android:icon="@mipmap/colorful"
      android:roundIcon="@mipmap/colorful_round"
      android:targetActivity=".MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity-alias>

    <activity
      android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
      android:theme="@style/SplashTheme"
      android:label="@string/app_name"
      android:launchMode="singleTask">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>

    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

    <meta-data
      android:name="com.google.firebase.messaging.default_notification_icon"
      android:resource="@mipmap/ic_stat_name"
    />
    
    <meta-data
      tools:replace="android:resource"
      android:name="com.google.firebase.messaging.default_notification_color"
      android:resource="@color/background"
    />

  </application>

</manifest>
```

**Comment by junioroga** [comment]
Your first activity-alias on MainActivitystandard must be enabled false, all activity-alias must be, enabled false. The props android:icon="@mipmap/colorful"
android:roundIcon="@mipmap/colorful_round"
Need be too in the <activity /> main.

**Comment by 0xc14m1z** [comment]
Maybe I'm missing something here.

The `MainActivitystandard` is the activity with the standard icon we provide.
I switched it back to `enable=false` to be sure but I still have the two icons around.

This is the updated XML part.

```xml
    <activity-alias
      android:name=".MainActivitystandard"
      android:enabled="false"
      android:icon="@mipmap/standard"
      android:roundIcon="@mipmap/standard_round"
      android:targetActivity=".MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity-alias>

    <activity-alias
      android:name=".MainActivitycolorful"
      android:enabled="false"
      android:icon="@mipmap/colorful"
      android:roundIcon="@mipmap/colorful_round"
      android:targetActivity=".MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity-alias>
```

I also added `android:icon="@mipmap/standard"` and `android:roundIcon="@mipmap/standard_round"` to the main activity but still, two icons:

```xml
  <application
    android:name=".MainApplication"
    android:label="@string/app_name"
    android:icon="@mipmap/standard"
    android:roundIcon="@mipmap/standard_round"
    android:allowBackup="false"
    android:theme="@style/AppTheme"
    android:fullBackupContent="@xml/appcenter_backup_rule">

    <activity
      android:name=".MainActivity"
      android:label="@string/app_name"
      android:icon="@mipmap/standard"
      android:roundIcon="@mipmap/standard_round"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
      android:launchMode="singleTask"
      android:screenOrientation="portrait"
      android:windowSoftInputMode="adjustResize"
      android:exported="true">
```

**Comment by junioroga** [comment]
Are you deleting the app before run it again?

**Comment by 0xc14m1z** [comment]
I delete the app before every test.
I have command for the android cleanup which does: `"android:cleanup": "rimraf android/.gradle android/build android/app/build"`.

But no, I don't run `react-native link` between each attempt. Let me try.

**Comment by junioroga** [comment]
Can you try, setting the package name before .MainActivitystandard, com.xxxxxx.MainActivitystandard and com.xxxxxx.MainActivitycolorful

**Comment by 0xc14m1z** [comment]
I did that too, but still have the double icons.
I know you're trying your best don't worry 🙂
We're following the same steps I tried before, it's cool to know that I had the same reasoning as you're having to troubleshoot this issue at least...

**Comment by caolong0204** [comment]
This is my manifest, and it's solved this issue

<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.longvu.appdemo">

  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <application android:name=".MainApplication" 
              android:label="@string/app_name" 
              android:icon="@mipmap/oldlogo" 
              android:allowBackup="false" 
              android:theme="@style/AppTheme">
    <activity android:name=".MainActivity" 
              android:label="@string/app_name" 
              android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" 
              android:launchMode="singleTask" 
              android:windowSoftInputMode="adjustResize">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>

    <activity-alias android:name="com.longvu.appdemo.MainActivityoldlogo" android:enabled="false" android:icon="@mipmap/oldlogo" android:targetActivity=".MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity-alias>
    <activity-alias android:name="com.longvu.appdemo.MainActivitynewlogo" android:enabled="false" android:icon="@mipmap/newlogo" android:targetActivity=".MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity-alias>

  </application>
</manifest>

**Comment by 0xc14m1z** [comment]
I tried to start from the example app and used all the suggestions received from @junioroga and the sample app is working!

Now, I tried with my own manifest but it's not, so I guess that the difficulty here might be around my manifest being way more complex than the sample one.

Would I need to move copy over all the aliases all the intent-filters maybe? 🤔

**Comment by 0xc14m1z** [comment]
I realized that the double icon is due to the splash screen activity:

```xml
<activity
  android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
  android:theme="@style/SplashTheme"
  android:label="@string/app_name"
  android:launchMode="singleTask">
  <intent-filter>
    <action android:name="android.intent.action.MAIN" />
    <category android:name="android.intent.category.LAUNCHER" />
  </intent-filter>
</activity>
```

When I disable it, it works well 😔
Ideas?

**Comment by skb1129** [comment]
@0xc14m1z try using this library for splash screen: https://github.com/crazycodeboy/react-native-splash-screen
I tried it once, did not give me any problems

**Comment by skb1129** [comment]
Closing as it is inactive

**Comment by ChiBao284** [comment]
> @0xc14m1z try using this library for splash screen: https://github.com/crazycodeboy/react-native-splash-screen I tried it once, did not give me any problems

App will be duplicated when using react-native-bootsplash library

**Comment by scaralfred** [comment]
Sadly still getting duplicated icons error.
Icons get duplicated multiple times.
Version 4.0.0

**Comment by zatteo** [comment]
> I realized that the double icon is due to the splash screen activity:
> 
> ```
> <activity
>   android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
>   android:theme="@style/SplashTheme"
>   android:label="@string/app_name"
>   android:launchMode="singleTask">
>   <intent-filter>
>     <action android:name="android.intent.action.MAIN" />
>     <category android:name="android.intent.category.LAUNCHER" />
>   </intent-filter>
> </activity>
> ```
> 
> When I disable it, it works well 😔 Ideas?

Setting `android:enabled="false"` in `RNBootSplashActivity` seems to solve the issue.

**Comment by longb1997** [comment]
still meet it, i do not use react-native-bootsplash or any library for splash screen. :(

**Comment by danklad** [comment]
I am not using react-native-bootsplash but it is still duplicating for me.

**Comment by LozytskyiA** [comment]
Doesnt use the react-native-bootsplash, but facing duplicate icons issue

**Comment by darshanbajania** [comment]
Removing  just `<category android:name="android.intent.category.LAUNCHER" />` from  the `<activity>` block fixed the duplicate icons issue.


### Before

```
  <activity
            android:name=".MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
            android:exported="true"
            android:launchMode="singleTask"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```

### After

```
  <activity
            android:name=".MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
            android:exported="true"
            android:launchMode="singleTask"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
            </intent-filter>
        </activity>
```

**Comment by GusttavoCastilho** [comment]
@0xc14m1z did you get a solution?

**Comment by kristalpithwa** [comment]
Note: 
- This is my manifest, and it's solved My issue,
1) MainActivity: No need for an enabled flag
2) First <activity-alias>: First activity-alias only android:enabled="true"
3) Other <activity-alias>: Other activity-aliases should be false android:enabled="false"
 <activity
            android:name=".MainActivity"
       android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
            android:exported="true"
            android:launchMode="singleTask"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
            </intent-filter>
        </activity>

        <activity-alias
            android:name=".MainActivityDefault"
            android:enabled="true"
            android:exported="true"
            android:icon="@mipmap/ic_launcher"
            android:targetActivity=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity-alias>

        <activity-alias
            android:name=".MainActivityLight"
            android:enabled="false"
            android:exported="true"
            android:icon="@mipmap/ic_launcher_light"
            android:targetActivity=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity-alias>

        <activity-alias
            android:name=".MainActivityDark"
            android:enabled="false"
            android:exported="true"
            android:icon="@mipmap/ic_launcher_dark"
            android:targetActivity=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity-alias>
    </application>

**Comment by Ohtico** [comment]
Hello, in v5 doesn't duplicate icon, but, when change icon, the app finish, why? maybe also people solved this?

**Comment by MarshalLeeeeee** [comment]
> Note:
> 
> * This is my manifest, and it's solved My issue,
> 
> 1. MainActivity: No need for an enabled flag
> 2. First : First activity-alias only android:enabled="true"
> 3. Other : Other activity-aliases should be false android:enabled="false"
>    
>    
>    
>    
>    
>    ```
>     <activity-alias
>         android:name=".MainActivityDefault"
>         android:enabled="true"
>         android:exported="true"
>         android:icon="@mipmap/ic_launcher"
>         android:targetActivity=".MainActivity">
>         <intent-filter>
>             <action android:name="android.intent.action.MAIN" />
>             <category android:name="android.intent.category.LAUNCHER" />
>         </intent-filter>
>     </activity-alias>
>    
>     <activity-alias
>         android:name=".MainActivityLight"
>         android:enabled="false"
>         android:exported="true"
>         android:icon="@mipmap/ic_launcher_light"
>         android:targetActivity=".MainActivity">
>         <intent-filter>
>             <action android:name="android.intent.action.MAIN" />
>             <category android:name="android.intent.category.LAUNCHER" />
>         </intent-filter>
>     </activity-alias>
>    
>     <activity-alias
>         android:name=".MainActivityDark"
>         android:enabled="false"
>         android:exported="true"
>         android:icon="@mipmap/ic_launcher_dark"
>         android:targetActivity=".MainActivity">
>         <intent-filter>
>             <action android:name="android.intent.action.MAIN" />
>             <category android:name="android.intent.category.LAUNCHER" />
>         </intent-filter>
>     </activity-alias>
>    ```

What is the intent filter for MainActivity in this case? I have duplicate icons right after install (even before the first installation) when both MainActivity and MainActivityDefault is enabled.
