### ISSUE TITLE
Setting the iOS app icon back to default

### ISSUE THREAD

**Issue by joe-yeomans** [skb1129/react-native-change-icon#46]
**Platform**
 - [x] iOS
 - [ ] Android

**Description**
Passing an empty string to `changeIcon(iconName)` should pass nil to `UIApplication.shared.setAlternateIconName(iconName)`. This will allow the default iOS icon to be set.

**To Reproduce**
1. Pass an empty string to the `changeIcon(iconName)` function. 

**Expected behavior**
This should set the default app icon back.

**Screenshots**

**Device (please complete the following information):**
 - Device: iphone 13
 - OS: iOS 15.0

**Versions**
 - react-native: 0.66.2
 - react-native-change-icon: 3.1.1

**Comment by cesargdm** [comment]
https://developer.apple.com/documentation/uikit/uiapplication/2806818-setalternateiconname

**Comment by skb1129** [comment]
To keep the flow similar in iOS and Android, we did not use this functionality provided by iOS.

**Comment by chmiiller** [comment]
So there's no way to set the app icon back to the default one? +1 for exposing this

**Comment by joe-yeomans** [comment]
@chmiiller The way I got around it is by adding the default icon as a second icon. This was you can switch between the two.

**Comment by skb1129** [comment]
Your default icon can be added as an alternate icon as well, this would give you the ability to switch back to default.
