### ISSUE TITLE
UI API called on a background thread

### ISSUE THREAD

**Issue by xclidongbo** [skb1129/react-native-change-icon#50]
Main Thread Checker: UI API called on a background thread: -[UIApplication supportsAlternateIcons]
Main Thread Checker: UI API called on a background thread: -[UIApplication alternateIconName]

**Comment by gary-cohen** [comment]
I'm seeing the same error and the first time it runs it takes a long time to prompt for the change.. I'm guessing this is why.

**Comment by skb1129** [comment]
https://github.com/skb1129/react-native-change-icon/pull/37
Can you please check this PR, will this fix the issue?

**Comment by gary-cohen** [comment]
@skb1129 Yes, this solves the problem.

**Comment by gary-cohen** [comment]
@skb1129 can you accept the PR 🙏

**Comment by skb1129** [comment]
Closing this issue as it is fixed
