### ISSUE TITLE
Update request (jcenter): remove usage of jcenter()

### ISSUE THREAD

**Issue by swatiredhu17** [skb1129/react-native-change-icon#51]
**Platform**
 - [ ] Android

**Description**
JCenter is going to be read-only. Are you planning to remove jCenter from build.gradle ?

**Code Snippet**
Path : react-native-change-icon/android/build.gradle
  repositories {
    google()
    jcenter()
  }

**Comment by skb1129** [comment]
@swatiredhu17 this issue is fixed in the latest release
