### ISSUE TITLE
I cannot change the icon

### ISSUE THREAD

**Issue by utiq** [skb1129/react-native-change-icon#59]
**Platform**
 - [X] iOS
 - [ ] Android

**Description**
The icon is empty
![image](https://user-images.githubusercontent.com/1144196/163070856-915ce2df-aaa9-494c-a74c-79c8a4cd0d14.png)

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Device: iPhone 13 (simulator)
 - OS: iOS 15.2
 - XCode Version 13.2.1

**Versions**
 - react-native: 0.67.3
 - react-native-change-icon: 3.2.0

**Code Snippet**
```
<key>CFBundleIcons</key>
	<dict>
		<key>CFBundleAlternateIcons</key>
		<dict>
			<key>gold</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>gold</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<string>NO</string>
			</dict>
			<key>white</key>
			<dict>
				<key>CFBundleIconFiles</key>
				<array>
					<string>white</string>
				</array>
				<key>UIPrerenderedIcon</key>
				<string>NO</string>
			</dict>
		</dict>
		<key>CFBundlePrimaryIcon</key>
		<dict>
			<key>CFBundleIconName</key>
			<string></string>
			<key>CFBundleIconFiles</key>
			<array>
				<string>gold</string>
			</array>
			<key>UIPrerenderedIcon</key>
			<false/>
		</dict>
		<key>UINewsstandIcon</key>
		<dict>
			<key>CFBundleIconFiles</key>
			<array>
				<string>gold</string>
			</array>
			<key>UINewsstandBindingType</key>
			<string>UINewsstandBindingTypeMagazine</string>
			<key>UINewsstandBindingEdge</key>
			<string>UINewsstandBindingEdgeLeft</string>
		</dict>
	</dict>
```
![image](https://user-images.githubusercontent.com/1144196/163071389-8c4f4bab-0e40-4e9b-8a60-ebac97f1fc01.png)

**Comment by o5faruk** [comment]
Try restarting the device. I had the same issue. It seems there is some icon caching issue on ios

**Comment by skb1129** [comment]
@utiq seems like a configuration error, please follow the steps mentioned in the readme.

**Comment by ghiculescualexandru** [comment]
I have followed the steps mentioned in the readme, however I encountered the same issue

**Comment by rohan-kadkol** [comment]
@skb1129 @utiq @ghiculescualexandru @o5faruk I am facing this exact same issue too, even after exactly following the steps in the README. I also used another brand new simulator to avoid any icon caching issues as mentioned in https://github.com/skb1129/react-native-change-icon/issues/59#issuecomment-1209490282. Same error on that too.

Can you please help? This is very urgent. Thanks.

**Comment by rohan-kadkol** [comment]
> @skb1129 @utiq @ghiculescualexandru @o5faruk I am facing this exact same issue too, even after exactly following the steps in the README. I also used another brand new simulator to avoid any icon caching issues as mentioned in [#59 (comment)](https://github.com/skb1129/react-native-change-icon/issues/59#issuecomment-1209490282). Same error on that too.
> 
> Can you please help? This is very urgent. Thanks.

I was able to fix it :) Sorry, it was a misunderstanding on my end. Here is more information: https://github.com/skb1129/react-native-change-icon/issues/40#issuecomment-1364414100
