### ISSUE TITLE
this.componentClass.split("MainActivity")[1] does not exist

### ISSUE THREAD

**Issue by nicolasdevienne** [skb1129/react-native-change-icon#69]
**Platform**
 - [ ] iOS
 - [x] Android

**Description**
I suggest you to change function getIcon() for Android :
```
        String currentIcon = this.componentClass.split("MainActivity")[1];
        promise.resolve(currentIcon.isEmpty() ? "default" : currentIcon);
```
by
```
        String[] currentIcon = this.componentClass.split("MainActivity");
        promise.resolve(currentIcon.length > 1 ? currentIcon[1] : "default");
```
Because when we launch for the first time the app, getCurrentActivity().getComponentName().getClassName() returns "com.xxx.MainActivity" and split function return an array with only one value, this.componentClass.split("MainActivity")[1] does not exist !

**Versions**
 - react-native-change-icon: [4.0.0]

**Comment by nicolasdevienne** [comment]
This issue appears only on simulator. On real device it's OK!

**Comment by Nitish33** [comment]
This issue will also occur when you open the app from App shortcut (Long press menu). Best to put a check on length instead of directly accessing it.
