### ISSUE TITLE
Cannot read property 'changeIcon' of null

### ISSUE THREAD

**Issue by GabiCtrlZ** [skb1129/react-native-change-icon#78]
**Platform**
 - [X] iOS
 - [ ] Android

**Description**
When trying to run the `changeIcon` function, I'm running into this error: "Cannot read property 'changeIcon' of null".
It seems that `NativeModules.ChangeIcon` returns null for some reason.

**To Reproduce**
Literally just followed the README example

**Device (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15.5

**Versions**
 - react-native: 0.70.6
 - react-native-change-icon: 4.0.0

**Comment by tmbradley** [comment]
Have you done a ```pod install``` after the ```npm install```?

**Comment by GabiCtrlZ** [comment]
@tmbradley Oh you're right, after running `pod install` everything works :)

**Comment by erie-e9** [comment]
Same error, using Hermes new structure.
react-native: 0.72.4
react-native-change-icon: 5.0.0

I ran pod install as @GabiCtrlZ mentioned, any idea? 

![Simulator Screenshot - iPhone 11-15 5 - 2023-09-27 at 12 57 57](https://github.com/skb1129/react-native-change-icon/assets/6515342/bdef1d39-dc47-44a5-85dc-2850a0fc7453)

**Comment by Bezaatay** [comment]
I have same issue 

<img width="353" alt="Image" src="https://github.com/user-attachments/assets/dfd17cce-72d5-44fa-a12f-5672b307cc6d" />
