### ISSUE TITLE
Icons via CodePush

### ISSUE THREAD

**Issue by ricardodolnl** [skb1129/react-native-change-icon#79]
_I know it's not an issue, it's a question. But I didn't know where else to put it._

Is it possible to use a icon that has been 'pushed' by Microsoft CodePush (or something similar) to the app?
I'm working on a sports club app and I would like the user to set there own club logo as icon. But I do not want to update the app via the app/play store every time to add new icons. I would like to add them via something like CodePush.

**Comment by skb1129** [comment]
@ricardodolnl dynamically adding/remoing icons does not work, for this to work, icons have to be part of the bundle itself, I have tried but found no solution for this, do let me know if you find a solution.
