### ISSUE TITLE
changeIcon not working on iPad

### ISSUE THREAD

**Issue by tmbradley** [skb1129/react-native-change-icon#80]
**Platform**
 - [x] iOS
 - [ ] Android

**Description**
When calling the ```changeIcon``` method on iPad (iPadOS version 16.2) the icon doesn't change. The promise gets returned successfully (i.e. no error to catch) but the icon does not update.

**To Reproduce**
1. Version iPad OS is at least version 16.2
2. Call changeIcon on iPad

**Expected behavior**
It is expected that the promise gets returned successfully and the icon is updated

**Device (please complete the following information):**
 - Device: iPad Air [5th Generation] (confirmed this is an issue on all iPad models
 - OS: iPadOS 16.2

**Versions**
 - react-native: 0.69.5
 - react-native-change-icon: 4.0.0

**Comment by mayniii** [comment]
it is working fine after i add **CFBundleIcons~ipad**
https://github.com/skb1129/react-native-change-icon/issues/62#issuecomment-1167306430

**Comment by skb1129** [comment]
the solution given by @mayniii works, closing this issue
