### ISSUE TITLE
Icon is not available on first run - Android only

### ISSUE THREAD

**Issue by otaviolbarbosa** [skb1129/react-native-change-icon#83]
**Platform**
 - [ ] iOS
 - [x] Android

**Description**
The scenarios I'm trying to cover is to have different icons for freemium and premium users. On iOs is working fine, but on Android, every first run of the app, icon is not available. If I close it completely and open it again, icon appears normally. This issue affects even push notification icons.

**To Reproduce**
1. 
2.

**Expected behavior**
App first run starts with app.

**Screenshots**
![image](https://user-images.githubusercontent.com/4713316/227540963-3b1f0d7d-ad06-4a2f-baee-70a9185183c3.png)
![image](https://user-images.githubusercontent.com/4713316/227541199-076e8034-73f7-46a0-9585-7c7d7d9d1a8c.png)

**Device (please complete the following information):**
 - Device: Samsung Galaxy A51
 - OS: Android 13

**Versions**
 - react-native: 0.67.2
 - react-native-change-icon: 4.0.0

**Code Snippet**
```
<activity-alias android:name="com.packagename.app.MainActivitylogofree"
  android:enabled="true"
  android:exported="true"
  android:icon="@mipmap/logofree"
  android:targetActivity=".MainActivity">
  <intent-filter>
    <action android:name="android.intent.action.MAIN" />
    <category android:name="android.intent.category.LAUNCHER" />
  </intent-filter>
</activity-alias>
<activity-alias android:name="com.packagename.app.MainActivitylogopremium"
  android:enabled="false"
  android:exported="true"
  android:icon="@mipmap/logopremium"
  android:targetActivity=".MainActivity">
  <intent-filter>
    <action android:name="android.intent.action.MAIN" />
    <category android:name="android.intent.category.LAUNCHER" />
  </intent-filter>
</activity-alias>
```

**Comment by skb1129** [comment]
@otaviolbarbosa please use v5 and use the updated docs for the setup
