### ISSUE TITLE
Icon Invalid issue

### ISSUE THREAD

**Issue by shkibrahim** [skb1129/react-native-change-icon#89]
**Platform**
 - [ ] iOS
 - [x] Android

**Description**

**To Reproduce**
1.
2.

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 12.1]

**Versions**
 - react-native: [e.g. 0.62.2]
 - react-native-change-icon: [e.g. 2.0.3]

**Code Snippet**
Please provide a minimal code snippet of the setup that you did to use this package. [e.g. AndroidManifest.xml]

**Comment by skb1129** [comment]
@shkibrahim please fill in the issue template otherwise i'll have to close this issue
