### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by SnakeHead** [skb1129/react-native-change-icon#9]
I've followed the instructions and reviewed the example app.  On iOS, I get a message telling me I've changed the icon, but when I look at the home screen, the app has not changed.  On Android, I see both the regular app icon for my app along with the secondary app I icon I created on the homescreen, prior to even running the change icon code.

**Comment by SnakeHead** [comment]
I got it to work by putting the icons at the root level (ie: not inside an App Icons folder).
**Note which should be added to the documentation for usage:**  To reset the icon, pass null:  `changeIcon(null)`

**Comment by DRanjith98** [comment]
I could change the icon in version 0.59 but in version 0.61 I'm getting the following error

null is not an object (evaluating RNChangeIcon.changeIcon)

**Comment by skizzo** [comment]
@SnakeHead how did you make this work on Android? I also have two icons next to each other without even calling `changeIcon()`.

**Comment by EQuimper** [comment]
Yes I can confirm this work only if you the icons in the root not in AppIcons folder
