### ISSUE TITLE
Feature: add suppressNotification option to iOS

### ISSUE THREAD

**Issue by maxinminax** [skb1129/react-native-change-icon#92]
By default, ios will show alert after change icon, please add option `suppressNotification` to disable that alert

**Comment by skb1129** [comment]
@maxinminax the icon change alert is a system triggered alert, Apple does not provide a way for us to disable it.
When we use setAlternateIconName, the system triggers a notification named UIApplicationDidChangeIconNotification to inform observers that the app icon has changed. This notification is part of the system's behavior and isn't meant to be directly disabled or suppressed by developers.
