### ISSUE TITLE
Alert message when change logo

### ISSUE THREAD

**Issue by BogdanRad** [skb1129/react-native-change-icon#96]
**Platform**
 - [X ] iOS
 - [X ] Android

**Description**
Can I remove this alert? Thank you!
<img width="380" alt="image" src="https://github.com/skb1129/react-native-change-icon/assets/40359109/860cfa46-0cb5-412a-97fb-b3024d3d98d6">

**Comment by skb1129** [comment]
iOS system alert, this cannot be disabled.

**Comment by bonnmh** [comment]
@BogdanRad  I think this code will help you a lot
https://github.com/skb1129/react-native-change-icon/pull/102

**Comment by BogdanRad** [comment]
> @BogdanRad I think this code will help you a lot #102

Amazing @bonnmh. Thank you!
